language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      env: ARCH="i686"
      compiler: "g++-5 -m32"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ccache
            - libssl1.0.0
            - bar
            - time
            - binutils
            - gcc-5
            - g++-5
            - gcc-5-multilib
            - g++-5-multilib
            - make:i386
            - libssl-dev:i386
            - gfortran-5
            - gfortran-5-multilib
    - os: linux
      env: ARCH="x86_64" GC_ANALYZE=1
      compiler: "g++-5 -m64"
    - os: linux
      env: ARCH="x86_64"
      compiler: "g++-5 -m64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ccache
            - libssl1.0.0
            - bar
            - time
            - g++-5
            - gfortran-5
    - os: osx
      env: ARCH="x86_64"
      osx_image: xcode8
cache: ccache
branches:
  only:
    - master
    - /^release-.*/
    - /^v\d+\.\d+\.\d+$/
notifications:
    email: false
before_install:
    - make check-whitespace
    - if [ `uname` = "Linux" -a $GC_ANALYZE = 0 ]; then
        contrib/travis_fastfail.sh || exit 1;
        mkdir -p $HOME/bin;
        ln -s /usr/bin/gcc-5 $HOME/bin/gcc;
        ln -s /usr/bin/g++-5 $HOME/bin/g++;
        ln -s /usr/bin/gfortran-5 $HOME/bin/gfortran;
        ln -s /usr/bin/gcc-5 $HOME/bin/x86_64-linux-gnu-gcc;
        ln -s /usr/bin/g++-5 $HOME/bin/x86_64-linux-gnu-g++;
        gcc --version;
        BAR="bar -i 30";
        BUILDOPTS="-j5 VERBOSE=1 FORCE_ASSERTIONS=1 LLVM_ASSERTIONS=1 USECCACHE=1";
        echo "override ARCH=$ARCH" >> Make.user;
        sudo sh -c "echo 0 > /proc/sys/net/ipv6/conf/lo/disable_ipv6";
        export JULIA_CPU_THREADS=4;
        export JULIA_TEST_MAXRSS_MB=1200;
        TESTSTORUN="all";
      elif [ `uname` = "Linux" ]; then
        BUILDOPTS="BINARYBUILDER_TRIPLET=x86_64-linux-gnu USE_BINARYBUILDER_LLVM=1 VERBOSE=1";
      elif [ `uname` = "Darwin" ]; then
        brew update;
        brew install -v jq pv ccache;
        export PATH="$(brew --prefix ccache)/libexec:$PATH";
        BAR="pv -i 30";
        contrib/travis_fastfail.sh || exit 1;
        brew tap staticfloat/julia > /dev/null;
        brew rm --force $(brew deps --HEAD julia);
        brew install -v gcc gmp mpfr pcre2 staticfloat/julia/openblas-julia staticfloat/julia/suite-sparse-julia staticfloat/juliadeps/libgfortran;
        BUILDOPTS="-j3 USECLANG=1 USECCACHE=1 BINARYBUILDER_TRIPLET=x86_64-apple-darwin14 BINARYBUILDER_LLVM_ASSERTS=1";
        BUILDOPTS="$BUILDOPTS USE_BINARYBUILDER_LLVM=1 LLVM_CONFIG=$TRAVIS_BUILD_DIR/usr/tools/llvm-config LLVM_SIZE=$TRAVIS_BUILD_DIR/usr/tools/llvm-size";
        BUILDOPTS="$BUILDOPTS VERBOSE=1 USE_BLAS64=0 SUITESPARSE_INC=-I$(brew --prefix suite-sparse-julia)/include FORCE_ASSERTIONS=1";
        BUILDOPTS="$BUILDOPTS LIBBLAS=-lopenblas LIBBLASNAME=libopenblas LIBLAPACK=-lopenblas LIBLAPACKNAME=libopenblas";
        for lib in SUITESPARSE BLAS LAPACK GMP MPFR PCRE LIBUNWIND; do
            BUILDOPTS="$BUILDOPTS USE_SYSTEM_$lib=1";
        done;
        export LDFLAGS="-L$(brew --prefix openblas-julia)/lib -L$(brew --prefix suite-sparse-julia)/lib";
        spawn_DYLD_FALLBACK_LIBRARY_PATH="/usr/local/lib:/lib:/usr/lib";
        spawn_DYLD_FALLBACK_LIBRARY_PATH+=":$(brew --prefix openblas-julia)/lib";
        spawn_DYLD_FALLBACK_LIBRARY_PATH+=":$(brew --prefix suite-sparse-julia)/lib";
        export JULIA_MACOS_SPAWN="DYLD_FALLBACK_LIBRARY_PATH=\"$spawn_DYLD_FALLBACK_LIBRARY_PATH\" \$1";
        export BUILDOPTS="$BUILDOPTS spawn=\$(JULIA_MACOS_SPAWN)";
        make $BUILDOPTS -C contrib -f repackage_system_suitesparse4.make;
        export JULIA_CPU_THREADS=2;
        export JULIA_TEST_MAXRSS_MB=600;
        TESTSTORUN="all --skip linalg/triangular subarray"; fi # TODO: re enable these if possible without timing out
    - echo "override JULIA_CPU_TARGET=generic;native" >> Make.user
    - wget http://http.debian.net/debian/pool/main/m/moreutils/moreutils_0.62.orig.tar.xz
    - tar -xJvf moreutils_0.62.orig.tar.xz && mv moreutils-0.62 moreutils
script:
    - echo BUILDOPTS=$BUILDOPTS
    - export BUILDOPTS
    - contrib/travis.sh
# uncomment the following if failures are suspected to be due to the out-of-memory killer
#    - dmesg
after_success:
    - if [ `uname` = "Linux" ] && [ $ARCH = "x86_64" ] && [ $GC_ANALYZE = 0 ]; then
        cd julia && make -C doc deploy; fi
